/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Ordenes extends javax.swing.JFrame {
    int Indice = 0;
    String Nombrepizza;
    ArrayList<Pizza> lista=new ArrayList<Pizza>();
    ArrayList<PizzaJal> lista2=new ArrayList<PizzaJal>();
    ArrayList<PizzaPG> lista3=new ArrayList<PizzaPG>();
    /**
     * Creates new form Ordenes
     */
    public Ordenes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTituloOrdenes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbsucursalO = new javax.swing.JLabel();
        SucursalOrdenes = new javax.swing.JComboBox<>();
        lbldescripcionO = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrdenes = new javax.swing.JTable();
        btnCrearOrden = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTituloOrdenes.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        txtTituloOrdenes.setForeground(new java.awt.Color(204, 0, 0));
        txtTituloOrdenes.setText("ORDENES");

        lbsucursalO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbsucursalO.setText("Sucursal:");

        SucursalOrdenes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SucursalOrdenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "El Progeso", "Jalapa" }));
        SucursalOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucursalOrdenesActionPerformed(evt);
            }
        });

        lbldescripcionO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldescripcionO.setText("Pizzas Disponibles: ");

        jTableOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Descripcion", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableOrdenes);

        btnCrearOrden.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCrearOrden.setForeground(new java.awt.Color(0, 204, 102));
        btnCrearOrden.setText("Crear Orden");
        btnCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOrdenActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbsucursalO)
                .addGap(18, 18, 18)
                .addComponent(SucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnSalir))
                    .addComponent(lbldescripcionO))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsucursalO)
                    .addComponent(SucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearOrden))
                .addGap(28, 28, 28)
                .addComponent(lbldescripcionO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        btnAdministracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdministracion.setForeground(new java.awt.Color(0, 102, 255));
        btnAdministracion.setText("Ir a Administracion");
        btnAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministracionMouseClicked(evt);
            }
        });
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloOrdenes)
                .addGap(92, 92, 92)
                .addComponent(btnAdministracion)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdministracion)
                    .addComponent(txtTituloOrdenes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnAdministracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministracionMouseClicked
        Administrador administrador = new Administrador();
        administrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministracionMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked
    
    public void mostrar()
    {
        String matris[][]=new String[lista.size()][3];
        String matris2[][]=new String[lista2.size()][3];
        String matris3[][]=new String[lista3.size()][3];
        
        
        switch(Indice){
            case 0:
                for (int i = 0; i < lista.size(); i++) {
            
                matris[i][0]=lista.get(i).getNombre();
                matris[i][1]=lista.get(i).getDescripcion();
                matris[i][2]=lista.get(i).getPrecio();
                }
                break;
            case 1:
                for (int i = 0; i < lista2.size(); i++) {
            
                matris2[i][0]=lista2.get(i).getNombre();
                matris2[i][1]=lista2.get(i).getDescripcion();
                matris2[i][2]=lista2.get(i).getPrecio();
                }
                break;
            case 2:
                for (int i = 0; i < lista3.size(); i++) {
            
                matris3[i][0]=lista3.get(i).getNombre();
                matris3[i][1]=lista3.get(i).getDescripcion();
                matris3[i][2]=lista3.get(i).getPrecio();
                }
                break;
        }
        switch (Indice){
            case 0:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                 matris,
                 new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                 }
                ));
                break;
            case 1:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                 matris2,
                 new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                 }
                ));
                break;
            case 2:
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                 matris3,
                 new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                 }
                ));
                break;
        }
    }
    private void SucursalOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalOrdenesActionPerformed
        Indice = SucursalOrdenes.getSelectedIndex();
        switch (Indice){
            case 0:
                mostrar();
              break;
            case 1:
                mostrar();
              break;
            case 2:
                mostrar();
              break;
        }
    }//GEN-LAST:event_SucursalOrdenesActionPerformed

    private void btnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOrdenActionPerformed
        JOptionPane.showMessageDialog(this, "Compra realizada con Exito!");
    }//GEN-LAST:event_btnCrearOrdenActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
    }//GEN-LAST:event_btnSalirActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SucursalOrdenes;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnCrearOrden;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableOrdenes;
    private javax.swing.JLabel lbldescripcionO;
    private javax.swing.JLabel lbsucursalO;
    private javax.swing.JLabel txtTituloOrdenes;
    // End of variables declaration//GEN-END:variables
}
